changed console files to fix breaks in operations.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2933,7 +2933,7 @@ echo "$as_me: error: Library requirements (glib >= 1.2.10 gtk+ >= 1.2.10) not me
   fi
 
 #
-ac_config_files="$ac_config_files Makefile include/Makefile lib/Makefile src/Makefile src/console/Makefile src/popup/Makefile"
+ac_config_files="$ac_config_files Makefile include/Makefile lib/Makefile src/Makefile src/console/Makefile src/popup/Makefile src/console2/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3259,9 +3259,10 @@ do
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "src/console/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/console/Makefile" ;;
   "src/popup/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/popup/Makefile" ;;
+  "src/console2/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/console2/Makefile" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "include/config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS include/config.h" ;;
-  *) { { echo "$as_me:3264: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3265: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3496,7 +3497,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3499: creating $ac_file" >&5
+    { echo "$as_me:3500: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3514,7 +3515,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3517: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3518: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3527,7 +3528,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3530: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3531: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3588,7 +3589,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:3591: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:3592: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -3599,7 +3600,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3602: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3603: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3612,7 +3613,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3615: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3616: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3729,7 +3730,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:3732: $ac_file is unchanged" >&5
+      { echo "$as_me:3733: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -3858,5 +3859,5 @@ fi
 ##
 ##
 echo ""
-echo "--- Now run make, binaries will be in ./bin ---"
+echo "--- Now run make ---"
 echo ""
